### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by 2570961835** [AbelChe/BlastWithCaptcha#4]
![1657592645380](https://user-images.githubusercontent.com/33596025/178395114-51662d3c-8a6b-4ce2-a1d4-cdc8fd090bbd.png)

**Comment by AbelChe** [comment]
感谢发现问题！
yaml新版本函数弃用问题，已修复，已合并到main分支
[https://github.com/AbelChe/BlastWithCaptcha/tree/0.2.1](https://github.com/AbelChe/BlastWithCaptcha/tree/0.2.1)
